# Generated by Django 4.2.3 on 2023-09-03 17:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('address_complement', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charges_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('deposit', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_immo.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_immo.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('source', models.CharField(choices=[('Locataire', 'Locataire'), ('CAF', 'CAF')], default='Locataire', max_length=25)),
                ('rental', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('charges', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_immo.contract')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('list_type', models.CharField(choices=[('Entrée', 'Entrée'), ('Sortie', 'Sortie')], default='Entrée', max_length=6)),
                ('comments', models.TextField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_immo.contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='occupant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_immo.occupant'),
        ),
    ]
