# Generated by Django 4.2.3 on 2023-07-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('address_complement', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charges_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
