# Generated by Django 4.2.3 on 2023-07-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0002_ocupant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ocupant',
            new_name='Occupant',
        ),
    ]
