# Generated by Django 4.2.3 on 2023-07-18 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0003_rename_ocupant_occupant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_immo.apartment')),
                ('ocupant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_immo.occupant')),
            ],
        ),
    ]
