# Generated by Django 4.2.3 on 2023-07-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0004_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='ocupant',
            new_name='occupant',
        ),
    ]
