# Generated by Django 4.2.3 on 2023-07-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0006_itemslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemslist',
            name='type',
        ),
        migrations.AddField(
            model_name='itemslist',
            name='list_type',
            field=models.CharField(choices=[('Entry', 'Entry Items List'), ('Exit', 'Exit Items List')], default='Entry', max_length=5),
        ),
    ]
