# Generated by Django 4.2.3 on 2023-07-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0007_remove_itemslist_type_itemslist_list_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_type', models.CharField(choices=[('Deposit', 'Deposit payment'), ('Rent', 'Monthly rent payment')], default='Rent', max_length=7)),
                ('payment_source', models.CharField(choices=[('Occupant', 'From Occupant'), ('CAF', 'From CAF')], default='Occupant', max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_immo.contract')),
            ],
        ),
    ]
