# Generated by Django 4.2.3 on 2023-07-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0013_alter_itemslist_list_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_source',
            field=models.CharField(choices=[('Locataire', 'Du locataire'), ('CAF', 'De la CAF')], default='Locataire', max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Dépôt de garantie', 'Dépôt de garantie'), ('Loyer (Charges incluses)', 'Loyer (Charges incluses)')], default='Loyer (Charges incluses)', max_length=25),
        ),
    ]
