# Generated by Django 4.2.3 on 2023-08-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0014_alter_payment_payment_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name=['%d/%m/%Y']),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(verbose_name=['%d/%m/%Y']),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_source',
            field=models.CharField(choices=[('Locataire', 'Locataire'), ('CAF', 'CAF')], default='Locataire', max_length=25),
        ),
    ]
