# Generated by Django 4.2.3 on 2023-08-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0015_alter_contract_end_date_alter_contract_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(),
        ),
    ]
