# Generated by Django 4.2.3 on 2023-08-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0016_alter_contract_end_date_alter_contract_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name=['%d/%m/%Y']),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(verbose_name=['%d/%m/%Y']),
        ),
        migrations.AlterField(
            model_name='itemslist',
            name='date',
            field=models.DateField(verbose_name=['%d/%m/%Y']),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(verbose_name=['%d/%m/%Y']),
        ),
    ]
