# Generated by Django 4.2.3 on 2023-08-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0017_alter_contract_end_date_alter_contract_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='itemslist',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(),
        ),
    ]
