# Generated by Django 4.2.3 on 2023-08-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0018_contract_deposit_paid_alter_contract_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='deposit_paid',
        ),
    ]
