# Generated by Django 4.2.3 on 2023-08-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0020_payment_charges_alter_itemslist_list_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='price',
            new_name='amount',
        ),
    ]
