# Generated by Django 4.2.3 on 2023-08-10 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0021_rename_price_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='rental',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_source',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='contract',
            name='deposit',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='itemslist',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
