# Generated by Django 4.2.3 on 2023-08-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0022_rename_amount_payment_rental_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
