# Generated by Django 4.2.3 on 2023-08-16 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0027_agency_alter_payment_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_immo.agency'),
        ),
    ]
