# Generated by Django 4.2.3 on 2023-08-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0028_contract_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='commission',
        ),
    ]
