# Generated by Django 4.2.3 on 2023-08-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0029_remove_agency_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='gestion_immo.agency'),
        ),
    ]
