# Generated by Django 4.2.3 on 2023-08-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0031_alter_contract_deposit_alter_payment_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='deposit',
            field=models.BooleanField(default=True),
        ),
    ]
