# Generated by Django 4.2.3 on 2023-08-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_immo', '0032_alter_contract_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
